version: '2'

networks:
  elk:

#volumes:
#  elasticsearch:
#    driver: local

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch:9200
      elasticsearch.username: elastic
      elasticsearch.password: changeme
      xpack.monitoring.ui.container.elasticsearch.enabled: "true"
      xpack.security.enabled: "false"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: elasticsearch_540
    networks:
      - elk
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:       
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

  headPlugin:
    image: mobz/elasticsearch-head:5
    container_name: head_540
    ports:
      - 9100:9100

  logstash:
    container_name: logstash_one_channel
    image: docker.elastic.co/logstash/logstash:7.14.1
    networks:
      - elk
    environment:
      XPACK_MONITORING_ENABLED: "false"
    ports:
      - 5046:5046
    volumes:
      - ./config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./config/pipelines:/usr/share/logstash/config/pipelines:ro